apiVersion: v1
kind: ConfigMap
metadata:
  name: barq-backend-config
  namespace: barq-fleet
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"
  ALLOWED_HOSTS: "*"
  CORS_ORIGINS: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: barq-frontend-config
  namespace: barq-fleet
data:
  VITE_API_URL: "/api/v1"
